apiVersion: v1
kind: Namespace
metadata:
  name: simple-router
---
apiVersion: v1
kind: Service
metadata:
  name: simple-router
  namespace: simple-router
  labels:
    app: simple-router
spec:
  selector:
    app: simple-router
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer
