name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      #run: docker build . --file Dockerfile --tag simple-router:$(date +%s)
      run: docker  build  --push -t  hugenet.jfrog.io/docker/hello-world:latest:1.0.0
